#Los perfiles DEV Y QA funcionan con h2.
#Perfiles DEV, QA, PROD
image:
  directory:
    event: images/events/
    profile: images/profiles/

spring:
  profiles:
    active: dev

#Cuidado con h2 y la entidad user ya que es una palabra reservada por lo visto.
#En mysql no ocurre este inconveniente.